version: '3.7'
services:
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:6.2.2-alpine

  backend:
    stdin_open: true
    tty: true
    build:
      context: backend
      dockerfile: Dockerfile
    command: python webbit/main.py
    volumes:
      - ./backend:/app/
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      DB_CONNECTION: sqlite://db.sqlite3
      PYTHONPATH: .

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app'
    #      - './frontend/node_modules:/app/node_modules'
    environment:
      - NODE_ENV=development
    command: npm run start

  rabbit:
    image: rabbitmq:3.8.14-management-alpine
    ports:
    - 15672:15672
