FROM python:3.11-slim

WORKDIR /app

# Install dev dependencies including watchfiles for hot reloading
COPY requirements.txt dev-requirements.txt ./
RUN pip install --no-cache-dir -r dev-requirements.txt watchfiles

# The actual application code will be mounted as a volume
# to support hot reloading, so we don't need to COPY it here

# Command will be provided by docker-compose
EXPOSE 8888