name: Backend lint and test

on: [push, pull_request]

jobs:
  lint_test:
    name: Lint backend code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install uv
        run: pip install uv

      - name: Setup uv cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: cd backend && uv pip install -e .[dev]

      - name: Run linters
        run: sh ./scripts/lint

      - name: Run tests
        env:
          DB_CONNECTION: sqlite://tests.sqlite3
        run: |
          sh ./scripts/test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
