name: Frontend ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint and build frontend
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm run lint
    - run: npm run build
#     - run: npm test
