name: Tests

on: [push, pull_request]
jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-18.04
#    services:
#      postgres:
#        image: postgres:11.5-alpine
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: postgres
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install dev-requirements.txt
      - name: Run tests
        env:
          DB_CONNECTION: sqlite://tests.sqlite3
        run: |
          USE_LOCAL_DB_FOR_TEST=true poetry run ./scripts/test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1